In [29]:
import pandas as pd
import numpy as np

In [30]:
inv = pd.read_csv('final_data/INV.csv')

In [31]:
pnrb = pd.read_csv('final_data/PNRB.csv')
sch = pd.read_csv('final_data/SCH.csv')

In [32]:
inv.head()

,InventoryId,ScheduleId,CarrierCode,Dep_Key,FlightNumber,AircraftType,DepartureDate,DepartureDateTime,ArrivalDateTime,DepartureAirport,...,PC_Oversold,PC_AvailableInventory,EC_TotalInventory,EC_BookedInventory,EC_Oversold,EC_AvailableInventory,FC_CD,BC_CD,PC_CD,EC_CD
0,INV-ZZ-2774494,SCH-ZZ-3400127,ZZ,ZZ20240505AMDHYD2223.0,2223.0,Boeing 777,05/05/2024,2024-05-05 10:52:00,2024-05-05 19:30:00,AMD,...,49,74,199,102,68,97,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
1,INV-ZZ-8029879,SCH-ZZ-3400127,ZZ,ZZ20240506AMDHYD2223.0,2223.0,Boeing 777,05/06/2024,2024-05-06 10:52:00,2024-05-06 19:30:00,AMD,...,47,72,202,106,64,96,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
2,INV-ZZ-6852033,SCH-ZZ-3400127,ZZ,ZZ20240507AMDHYD2223.0,2223.0,Boeing 777,05/07/2024,2024-05-07 10:52:00,2024-05-07 19:30:00,AMD,...,44,61,197,114,56,83,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
3,INV-ZZ-7065859,SCH-ZZ-3400127,ZZ,ZZ20240508AMDHYD2223.0,2223.0,Boeing 777,05/08/2024,2024-05-08 10:52:00,2024-05-08 19:30:00,AMD,...,51,66,192,103,67,89,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
4,INV-ZZ-1595392,SCH-ZZ-3400127,ZZ,ZZ20240512AMDHYD2223.0,2223.0,Boeing 777,05/12/2024,2024-05-12 10:52:00,2024-05-12 19:30:00,AMD,...,48,66,197,107,63,90,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."

In [33]:
    def remove_last_two_chars(s):
        return s[:-2]

inv['Dep_Key'] = inv['Dep_Key'].astype(str)

In [34]:
inv['Dep_Key'] = inv['Dep_Key'].apply(remove_last_two_chars)

In [35]:
inv.head()

,InventoryId,ScheduleId,CarrierCode,Dep_Key,FlightNumber,AircraftType,DepartureDate,DepartureDateTime,ArrivalDateTime,DepartureAirport,...,PC_Oversold,PC_AvailableInventory,EC_TotalInventory,EC_BookedInventory,EC_Oversold,EC_AvailableInventory,FC_CD,BC_CD,PC_CD,EC_CD
0,INV-ZZ-2774494,SCH-ZZ-3400127,ZZ,ZZ20240505AMDHYD2223,2223.0,Boeing 777,05/05/2024,2024-05-05 10:52:00,2024-05-05 19:30:00,AMD,...,49,74,199,102,68,97,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
1,INV-ZZ-8029879,SCH-ZZ-3400127,ZZ,ZZ20240506AMDHYD2223,2223.0,Boeing 777,05/06/2024,2024-05-06 10:52:00,2024-05-06 19:30:00,AMD,...,47,72,202,106,64,96,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
2,INV-ZZ-6852033,SCH-ZZ-3400127,ZZ,ZZ20240507AMDHYD2223,2223.0,Boeing 777,05/07/2024,2024-05-07 10:52:00,2024-05-07 19:30:00,AMD,...,44,61,197,114,56,83,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
3,INV-ZZ-7065859,SCH-ZZ-3400127,ZZ,ZZ20240508AMDHYD2223,2223.0,Boeing 777,05/08/2024,2024-05-08 10:52:00,2024-05-08 19:30:00,AMD,...,51,66,192,103,67,89,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."
4,INV-ZZ-1595392,SCH-ZZ-3400127,ZZ,ZZ20240512AMDHYD2223,2223.0,Boeing 777,05/12/2024,2024-05-12 10:52:00,2024-05-12 19:30:00,AMD,...,48,66,197,107,63,90,"{'F': 25, 'P': 17}","{'C': 34, 'J': 26, 'Z': 26}","{'Q': 38, 'R': 25, 'S': 13, 'T': 13, 'H': 25, ...","{'Y': 13, 'A': 13, 'B': 6, 'D': 6, 'E': 6, 'G'..."

In [38]:
pnrb[~pnrb['DEP_KEY'].isin(inv['Dep_Key'])]

Empty DataFrame
Columns: [RECLOC, CREATION_DTZ, DEP_KEY, ACTION_CD, COS_CD, SEG_SEQ, SEG_TOTAL, PAX_CNT, CARRIER_CD, FLT_NUM, ORIG_CD, DEST_CD, DEP_DT, DEP_DTML, ARR_DTML, DEP_DTMZ, ARR_DTMZ]
Index: []

In [37]:
i_pnr

Empty DataFrame
Columns: [RECLOC, CREATION_DTZ, DEP_KEY, ACTION_CD, COS_CD, SEG_SEQ, SEG_TOTAL, PAX_CNT, CARRIER_CD, FLT_NUM, ORIG_CD, DEST_CD, DEP_DT, DEP_DTML, ARR_DTML, DEP_DTMZ, ARR_DTMZ]
Index: []

In [39]:
len(inv)

2012

In [40]:
len(pnrb)

78184

In [41]:
len(sch)

90

In [42]:
pnrb.head()

,RECLOC,CREATION_DTZ,DEP_KEY,ACTION_CD,COS_CD,SEG_SEQ,SEG_TOTAL,PAX_CNT,CARRIER_CD,FLT_NUM,ORIG_CD,DEST_CD,DEP_DT,DEP_DTML,ARR_DTML,DEP_DTMZ,ARR_DTMZ
0,DRGS80,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,4,3,ZZ,2504,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
1,YEZQ47,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,2,4,ZZ,2504,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
2,JDDM40,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,3,2,ZZ,2504,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
3,AVFF16,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,4,1,ZZ,2504,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
4,DBLE79,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,2,2,ZZ,2504,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47

In [43]:
pnrb[pnrb['RECLOC']=='JDDM40']

,RECLOC,CREATION_DTZ,DEP_KEY,ACTION_CD,COS_CD,SEG_SEQ,SEG_TOTAL,PAX_CNT,CARRIER_CD,FLT_NUM,ORIG_CD,DEST_CD,DEP_DT,DEP_DTML,ARR_DTML,DEP_DTMZ,ARR_DTMZ
2,JDDM40,3/2/2024 16:35,ZZ20240403BLRCCU2504,GN,FirstClass,1,3,2,ZZ,2504,BLR,CCU,4/3/2024,4/3/2024 15:35,4/3/2024 18:17,4/3/2024 10:05,4/3/2024 12:47
86,JDDM40,3/2/2024 16:35,ZZ20240406CCUHYD3723,GN,FirstClass,2,3,2,ZZ,3723,CCU,HYD,4/6/2024,4/6/2024 16:19,4/7/2024 0:54,4/6/2024 10:49,4/6/2024 19:24
87,JDDM40,3/2/2024 16:35,ZZ20240507HYDBLR2887,HL,FirstClass,3,3,2,ZZ,2887,HYD,BLR,5/7/2024,5/7/2024 0:30,5/7/2024 13:36,5/6/2024 19:00,5/7/2024 8:06

In [44]:
inv[inv['FlightNumber']==3723]

,InventoryId,ScheduleId,CarrierCode,Dep_Key,FlightNumber,AircraftType,DepartureDate,DepartureDateTime,ArrivalDateTime,DepartureAirport,...,PC_Oversold,PC_AvailableInventory,EC_TotalInventory,EC_BookedInventory,EC_Oversold,EC_AvailableInventory,FC_CD,BC_CD,PC_CD,EC_CD
26,INV-ZZ-5183618,SCH-ZZ-6095474,ZZ,ZZ20240407HYDAMD3723,3723.0,Airbus A320 Neo,04/07/2024,2024-04-07 20:40:00,2024-04-08 12:24:00,HYD,...,15,24,82,50,22,32,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
27,INV-ZZ-8561943,SCH-ZZ-6095474,ZZ,ZZ20240410HYDAMD3723,3723.0,Airbus A320 Neo,04/10/2024,2024-04-10 20:40:00,2024-04-11 12:24:00,HYD,...,13,23,82,53,19,29,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
28,INV-ZZ-1703048,SCH-ZZ-6095474,ZZ,ZZ20240411HYDAMD3723,3723.0,Airbus A320 Neo,04/11/2024,2024-04-11 20:40:00,2024-04-12 12:24:00,HYD,...,18,27,82,47,25,35,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
29,INV-ZZ-1835306,SCH-ZZ-6095474,ZZ,ZZ20240413HYDAMD3723,3723.0,Airbus A320 Neo,04/13/2024,2024-04-13 20:40:00,2024-04-14 12:24:00,HYD,...,18,24,81,49,23,32,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
30,INV-ZZ-1644109,SCH-ZZ-6095474,ZZ,ZZ20240414HYDAMD3723,3723.0,Airbus A320 Neo,04/14/2024,2024-04-14 20:40:00,2024-04-15 12:24:00,HYD,...,15,24,81,50,22,31,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
31,INV-ZZ-6221422,SCH-ZZ-6095474,ZZ,ZZ20240417HYDAMD3723,3723.0,Airbus A320 Neo,04/17/2024,2024-04-17 20:40:00,2024-04-18 12:24:00,HYD,...,18,27,81,47,25,34,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
32,INV-ZZ-1535659,SCH-ZZ-6095474,ZZ,ZZ20240418HYDAMD3723,3723.0,Airbus A320 Neo,04/18/2024,2024-04-18 20:40:00,2024-04-19 12:24:00,HYD,...,18,25,82,48,24,34,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
33,INV-ZZ-9961664,SCH-ZZ-6095474,ZZ,ZZ20240420HYDAMD3723,3723.0,Airbus A320 Neo,04/20/2024,2024-04-20 20:40:00,2024-04-21 12:24:00,HYD,...,19,30,82,45,27,37,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
34,INV-ZZ-6246289,SCH-ZZ-6095474,ZZ,ZZ20240421HYDAMD3723,3723.0,Airbus A320 Neo,04/21/2024,2024-04-21 20:40:00,2024-04-22 12:24:00,HYD,...,17,23,82,50,22,32,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
35,INV-ZZ-1701449,SCH-ZZ-6095474,ZZ,ZZ20240424HYDAMD3723,3723.0,Airbus A320 Neo,04/24/2024,2024-04-24 20:40:00,2024-04-25 12:24:00,HYD,...,20,28,81,45,27,36,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
36,INV-ZZ-6584575,SCH-ZZ-6095474,ZZ,ZZ20240425HYDAMD3723,3723.0,Airbus A320 Neo,04/25/2024,2024-04-25 20:40:00,2024-04-26 12:24:00,HYD,...,21,29,85,45,27,40,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
37,INV-ZZ-9541445,SCH-ZZ-6095474,ZZ,ZZ20240427HYDAMD3723,3723.0,Airbus A320 Neo,04/27/2024,2024-04-27 20:40:00,2024-04-28 12:24:00,HYD,...,16,26,81,48,24,33,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
38,INV-ZZ-1585088,SCH-ZZ-6095474,ZZ,ZZ20240428HYDAMD3723,3723.0,Airbus A320 Neo,04/28/2024,2024-04-28 20:40:00,2024-04-29 12:24:00,HYD,...,18,26,83,48,24,35,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
39,INV-ZZ-8250797,SCH-ZZ-6095474,ZZ,ZZ20240501HYDAMD3723,3723.0,Airbus A320 Neo,05/01/2024,2024-05-01 20:40:00,2024-05-02 12:24:00,HYD,...,17,27,81,47,25,34,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
40,INV-ZZ-1225790,SCH-ZZ-6095474,ZZ,ZZ20240502HYDAMD3723,3723.0,Airbus A320 Neo,05/02/2024,2024-05-02 20:40:00,2024-05-03 12:24:00,HYD,...,19,27,82,46,26,36,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
41,INV-ZZ-9333293,SCH-ZZ-6095474,ZZ,ZZ20240504HYDAMD3723,3723.0,Airbus A320 Neo,05/04/2024,2024-05-04 20:40:00,2024-05-05 12:24:00,HYD,...,16,26,86,50,22,36,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
42,INV-ZZ-9341601,SCH-ZZ-6095474,ZZ,ZZ20240505HYDAMD3723,3723.0,Airbus A320 Neo,05/05/2024,2024-05-05 20:40:00,2024-05-06 12:24:00,HYD,...,22,31,79,40,32,39,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
43,INV-ZZ-1129237,SCH-ZZ-6095474,ZZ,ZZ20240508HYDAMD3723,3723.0,Airbus A320 Neo,05/08/2024,2024-05-08 20:40:00,2024-05-09 12:24:00,HYD,...,20,30,85,45,27,40,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
44,INV-ZZ-3646764,SCH-ZZ-6095474,ZZ,ZZ20240509HYDAMD3723,3723.0,Airbus A320 Neo,05/09/2024,2024-05-09 20:40:00,2024-05-10 12:24:00,HYD,...,21,29,80,43,29,37,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
45,INV-ZZ-4518400,SCH-ZZ-6095474,ZZ,ZZ20240511HYDAMD3723,3723.0,Airbus A320 Neo,05/11/2024,2024-05-11 20:40:00,2024-05-12 12:24:00,HYD,...,21,28,86,47,25,39,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
46,INV-ZZ-6567308,SCH-ZZ-6095474,ZZ,ZZ20240512HYDAMD3723,3723.0,Airbus A320 Neo,05/12/2024,2024-05-12 20:40:00,2024-05-13 12:24:00,HYD,...,19,27,82,46,26,36,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
47,INV-ZZ-5788104,SCH-ZZ-6095474,ZZ,ZZ20240515HYDAMD3723,3723.0,Airbus A320 Neo,05/15/2024,2024-05-15 20:40:00,2024-05-16 12:24:00,HYD,...,19,28,81,45,27,36,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
48,INV-ZZ-8327613,SCH-ZZ-6095474,ZZ,ZZ20240516HYDAMD3723,3723.0,Airbus A320 Neo,05/16/2024,2024-05-16 20:40:00,2024-05-17 12:24:00,HYD,...,22,30,84,43,29,41,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
49,INV-ZZ-6297563,SCH-ZZ-6095474,ZZ,ZZ20240518HYDAMD3723,3723.0,Airbus A320 Neo,05/18/2024,2024-05-18 20:40:00,2024-05-19 12:24:00,HYD,...,20,29,84,45,27,39,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
50,INV-ZZ-2307618,SCH-ZZ-6095474,ZZ,ZZ20240519HYDAMD3723,3723.0,Airbus A320 Neo,05/19/2024,2024-05-19 20:40:00,2024-05-20 12:24:00,HYD,...,23,29,82,43,29,39,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
51,INV-ZZ-9346309,SCH-ZZ-6095474,ZZ,ZZ20240522HYDAMD3723,3723.0,Airbus A320 Neo,05/22/2024,2024-05-22 20:40:00,2024-05-23 12:24:00,HYD,...,24,31,79,39,33,40,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
371,INV-ZZ-6903609,SCH-ZZ-7068651,ZZ,ZZ20240406CCUHYD3723,3723.0,Boeing 787,04/06/2024,2024-04-06 16:19:00,2024-04-07 00:54:00,CCU,...,23,34,120,75,33,45,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
372,INV-ZZ-2017253,SCH-ZZ-7068651,ZZ,ZZ20240407CCUHYD3723,3723.0,Boeing 787,04/07/2024,2024-04-07 16:19:00,2024-04-08 00:54:00,CCU,...,25,38,127,75,33,52,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
373,INV-ZZ-4864835,SCH-ZZ-7068651,ZZ,ZZ20240411CCUHYD3723,3723.0,Boeing 787,04/11/2024,2024-04-11 16:19:00,2024-04-12 00:54:00,CCU,...,28,37,121,71,37,50,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
374,INV-ZZ-4078402,SCH-ZZ-7068651,ZZ,ZZ20240413CCUHYD3723,3723.0,Boeing 787,04/13/2024,2024-04-13 16:19:00,2024-04-14 00:54:00,CCU,...,23,35,122,76,32,46,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
375,INV-ZZ-5186934,SCH-ZZ-7068651,ZZ,ZZ20240414CCUHYD3723,3723.0,Boeing 787,04/14/2024,2024-04-14 16:19:00,2024-04-15 00:54:00,CCU,...,26,42,126,71,37,55,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
376,INV-ZZ-3853891,SCH-ZZ-7068651,ZZ,ZZ20240418CCUHYD3723,3723.0,Boeing 787,04/18/2024,2024-04-18 16:19:00,2024-04-19 00:54:00,CCU,...,30,39,126,72,36,54,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
377,INV-ZZ-8513261,SCH-ZZ-7068651,ZZ,ZZ20240420CCUHYD3723,3723.0,Boeing 787,04/20/2024,2024-04-20 16:19:00,2024-04-21 00:54:00,CCU,...,27,39,120,70,38,50,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
378,INV-ZZ-9747842,SCH-ZZ-7068651,ZZ,ZZ20240421CCUHYD3723,3723.0,Boeing 787,04/21/2024,2024-04-21 16:19:00,2024-04-22 00:54:00,CCU,...,21,36,128,80,28,48,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
379,INV-ZZ-9046597,SCH-ZZ-7068651,ZZ,ZZ20240425CCUHYD3723,3723.0,Boeing 787,04/25/2024,2024-04-25 16:19:00,2024-04-26 00:54:00,CCU,...,25,37,129,78,30,51,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
380,INV-ZZ-7900668,SCH-ZZ-7068651,ZZ,ZZ20240427CCUHYD3723,3723.0,Boeing 787,04/27/2024,2024-04-27 16:19:00,2024-04-28 00:54:00,CCU,...,29,43,120,66,42,54,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
381,INV-ZZ-1050389,SCH-ZZ-7068651,ZZ,ZZ20240428CCUHYD3723,3723.0,Boeing 787,04/28/2024,2024-04-28 16:19:00,2024-04-29 00:54:00,CCU,...,32,41,119,65,43,54,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
382,INV-ZZ-9603106,SCH-ZZ-7068651,ZZ,ZZ20240502CCUHYD3723,3723.0,Boeing 787,05/02/2024,2024-05-02 16:19:00,2024-05-03 00:54:00,CCU,...,23,39,124,74,34,50,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
383,INV-ZZ-7772604,SCH-ZZ-7068651,ZZ,ZZ20240504CCUHYD3723,3723.0,Boeing 787,05/04/2024,2024-05-04 16:19:00,2024-05-05 00:54:00,CCU,...,29,41,127,71,37,56,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
384,INV-ZZ-1683934,SCH-ZZ-7068651,ZZ,ZZ20240505CCUHYD3723,3723.0,Boeing 787,05/05/2024,2024-05-05 16:19:00,2024-05-06 00:54:00,CCU,...,28,41,119,67,41,52,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
385,INV-ZZ-8978958,SCH-ZZ-7068651,ZZ,ZZ20240509CCUHYD3723,3723.0,Boeing 787,05/09/2024,2024-05-09 16:19:00,2024-05-10 00:54:00,CCU,...,34,44,127,65,43,62,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
386,INV-ZZ-9803887,SCH-ZZ-7068651,ZZ,ZZ20240511CCUHYD3723,3723.0,Boeing 787,05/11/2024,2024-05-11 16:19:00,2024-05-12 00:54:00,CCU,...,33,48,124,62,46,62,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
387,INV-ZZ-1203243,SCH-ZZ-7068651,ZZ,ZZ20240512CCUHYD3723,3723.0,Boeing 787,05/12/2024,2024-05-12 16:19:00,2024-05-13 00:54:00,CCU,...,27,41,121,69,39,52,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
388,INV-ZZ-6514059,SCH-ZZ-7068651,ZZ,ZZ20240516CCUHYD3723,3723.0,Boeing 787,05/16/2024,2024-05-16 16:19:00,2024-05-17 00:54:00,CCU,...,35,49,123,60,48,63,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
389,INV-ZZ-6636935,SCH-ZZ-7068651,ZZ,ZZ20240518CCUHYD3723,3723.0,Boeing 787,05/18/2024,2024-05-18 16:19:00,2024-05-19 00:54:00,CCU,...,35,48,124,61,47,63,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
390,INV-ZZ-6134765,SCH-ZZ-7068651,ZZ,ZZ20240519CCUHYD3723,3723.0,Boeing 787,05/19/2024,2024-05-19 16:19:00,2024-05-20 00:54:00,CCU,...,33,47,127,64,44,63,"{'F': 16, 'P': 11}","{'C': 22, 'J': 16, 'Z': 16}","{'Q': 24, 'R': 16, 'S': 8, 'T': 8, 'H': 16, 'M...","{'Y': 8, 'A': 8, 'B': 4, 'D': 4, 'E': 4, 'G': ..."
1972,INV-ZZ-5788471,SCH-ZZ-2790389,ZZ,ZZ20240423GAUPNQ3723,3723.0,Boeing 717,04/23/2024,2024-04-23 01:26:00,2024-04-23 20:43:00,GAU,...,10,15,45,26,14,19,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1973,INV-ZZ-1013270,SCH-ZZ-2790389,ZZ,ZZ20240426GAUPNQ3723,3723.0,Boeing 717,04/26/2024,2024-04-26 01:26:00,2024-04-26 20:43:00,GAU,...,10,14,46,27,13,19,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1974,INV-ZZ-5361019,SCH-ZZ-2790389,ZZ,ZZ20240430GAUPNQ3723,3723.0,Boeing 717,04/30/2024,2024-04-30 01:26:00,2024-04-30 20:43:00,GAU,...,9,14,47,28,12,19,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1975,INV-ZZ-5645584,SCH-ZZ-2790389,ZZ,ZZ20240503GAUPNQ3723,3723.0,Boeing 717,05/03/2024,2024-05-03 01:26:00,2024-05-03 20:43:00,GAU,...,10,15,45,26,14,19,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1976,INV-ZZ-3164285,SCH-ZZ-2790389,ZZ,ZZ20240507GAUPNQ3723,3723.0,Boeing 717,05/07/2024,2024-05-07 01:26:00,2024-05-07 20:43:00,GAU,...,10,15,47,26,14,21,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1977,INV-ZZ-1733836,SCH-ZZ-2790389,ZZ,ZZ20240510GAUPNQ3723,3723.0,Boeing 717,05/10/2024,2024-05-10 01:26:00,2024-05-10 20:43:00,GAU,...,11,14,47,26,14,21,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1978,INV-ZZ-4592881,SCH-ZZ-2790389,ZZ,ZZ20240514GAUPNQ3723,3723.0,Boeing 717,05/14/2024,2024-05-14 01:26:00,2024-05-14 20:43:00,GAU,...,12,16,48,25,15,23,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1979,INV-ZZ-9373766,SCH-ZZ-2790389,ZZ,ZZ20240517GAUPNQ3723,3723.0,Boeing 717,05/17/2024,2024-05-17 01:26:00,2024-05-17 20:43:00,GAU,...,13,16,46,24,16,22,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1980,INV-ZZ-5116443,SCH-ZZ-2790389,ZZ,ZZ20240521GAUPNQ3723,3723.0,Boeing 717,05/21/2024,2024-05-21 01:26:00,2024-05-21 20:43:00,GAU,...,12,16,46,25,15,21,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1981,INV-ZZ-8763917,SCH-ZZ-2790389,ZZ,ZZ20240524GAUPNQ3723,3723.0,Boeing 717,05/24/2024,2024-05-24 01:26:00,2024-05-24 20:43:00,GAU,...,12,16,46,24,16,22,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1982,INV-ZZ-6606395,SCH-ZZ-2790389,ZZ,ZZ20240528GAUPNQ3723,3723.0,Boeing 717,05/28/2024,2024-05-28 01:26:00,2024-05-28 20:43:00,GAU,...,14,18,44,21,19,23,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1983,INV-ZZ-2749749,SCH-ZZ-2790389,ZZ,ZZ20240531GAUPNQ3723,3723.0,Boeing 717,05/31/2024,2024-05-31 01:26:00,2024-05-31 20:43:00,GAU,...,13,17,46,23,17,23,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."
1984,INV-ZZ-3952774,SCH-ZZ-2790389,ZZ,ZZ20240604GAUPNQ3723,3723.0,Boeing 717,06/04/2024,2024-06-04 01:26:00,2024-06-04 20:43:00,GAU,...,14,19,44,20,20,24,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."

In [46]:
len(pnrb[~pnrb['DEP_KEY'].isin(inv['Dep_Key'])])

0

In [49]:
inv[inv['Dep_Key'] == 'ZZ20240624GAUPNQ3440']

,InventoryId,ScheduleId,CarrierCode,Dep_Key,FlightNumber,AircraftType,DepartureDate,DepartureDateTime,ArrivalDateTime,DepartureAirport,...,PC_Oversold,PC_AvailableInventory,EC_TotalInventory,EC_BookedInventory,EC_Oversold,EC_AvailableInventory,FC_CD,BC_CD,PC_CD,EC_CD
2011,INV-ZZ-1560576,SCH-ZZ-9762124,ZZ,ZZ20240624GAUPNQ3440,3440.0,Boeing 757,06/24/2024,2024-06-24 15:57:00,2024-06-25 05:13:00,GAU,...,34,42,99,40,43,59,"{'F': 12, 'P': 8}","{'C': 16, 'J': 12, 'Z': 12}","{'Q': 19, 'R': 12, 'S': 6, 'T': 6, 'H': 12, 'M...","{'Y': 6, 'A': 6, 'B': 3, 'D': 3, 'E': 3, 'G': ..."

In [50]:
inv['Dep_Key'] = inv['Dep_Key'][:-2]

In [51]:
len(inv)

2012

In [52]:
len(pnrb[pnrb['ACTION_CD']=='XX'])

19181

In [54]:
cancelled_flights = pd.read_csv('final_data/cancelled.csv')

In [55]:
cancelled_flights

,InventoryId,ScheduleId,CarrierCode,Dep_Key,FlightNumber,AircraftType,DepartureDate,DepartureDateTime,ArrivalDateTime,DepartureAirport,...,PC_Oversold,PC_AvailableInventory,EC_TotalInventory,EC_BookedInventory,EC_Oversold,EC_AvailableInventory,FC_CD,BC_CD,PC_CD,EC_CD
0,INV-ZZ-8327613,SCH-ZZ-6095474,ZZ,ZZ20240516HYDAMD3723.0,3723,Airbus A320 Neo,05/16/2024,5/16/2024 20:40,5/17/2024 12:24,HYD,...,22,30,84,43,29,41,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
1,INV-ZZ-6246289,SCH-ZZ-6095474,ZZ,ZZ20240421HYDAMD3723.0,3723,Airbus A320 Neo,04/21/2024,4/21/2024 20:40,4/22/2024 12:24,HYD,...,17,23,82,50,22,32,"{'F': 11, 'P': 7}","{'C': 14, 'J': 11, 'Z': 11}","{'Q': 16, 'R': 11, 'S': 5, 'T': 5, 'H': 11, 'M...","{'Y': 5, 'A': 5, 'B': 3, 'D': 3, 'E': 3, 'G': ..."
2,INV-ZZ-3520896,SCH-ZZ-6036812,ZZ,ZZ20240606DELAMD2167.0,2167,Boeing 717,6/6/2024,6/6/2024 23:11,6/7/2024 0:42,DEL,...,15,19,45,20,20,25,"{'F': 6, 'P': 4}","{'C': 8, 'J': 6, 'Z': 6}","{'Q': 9, 'R': 6, 'S': 3, 'T': 3, 'H': 6, 'M': 3}","{'Y': 3, 'A': 3, 'B': 2, 'D': 2, 'E': 2, 'G': ..."